mod store;
use store::*;

fn main() {
    let mut store: Store<String, i32> = Store::new();
    store.mutate_observable(1);
    store.checkpoint();
    store.ver_list();
    println!("Saved first version!");
    store.mutate_observable(1000);
    store.checkpoint();
    store.mutate_observable(1000);
    store.checkpoint();
    store.mutate_observable(1000);
    store.checkpoint();
    store.mutate_observable(1000);
    store.checkpoint();
    store.ver_list();
    store.rollback("0.3".to_string());
    store.ver_list();
    println!("Rollbacked to 0.3!");
    store.mutate_observable(1000);
    store.checkpoint();
    store.mutate_observable(1000);
    store.checkpoint();
    store.mutate_observable(1000);
    store.checkpoint();
    store.mutate_observable(1000);
    store.checkpoint();
    store.mutate_observable(1000);
    store.checkpoint();
    store.mutate_observable(1000);
    store.checkpoint();
    store.mutate_observable(1000);
    store.checkpoint();
    store.mutate_observable(1000);
    store.checkpoint();
    store.mutate_observable(1000);
    store.checkpoint();
    store.mutate_observable(1000);
    store.checkpoint();
    store.mutate_observable(1000);
    store.checkpoint();
    store.ver_list();
    store.prune();
    store.ver_list();
    println!("Pruned to the last one!");
    store.mutate_observable(1000);
    store.checkpoint();
    store.ver_list();
}